const button = document.getElementById("copiumBtn");
const fundBtn = document.getElementById("fundBtn");
const message = document.getElementById("message");
const memeText = document.getElementById("memeText");

const updates = [
  "Investor update: we are pivoting to AI.",
  "The AI is just Jacob with ChatGPT open.",
  "We accidentally spent the budget on tacos.",
  "Current company valuation: one subway cookie.",
  "We had a roadmap. We lost it.",
  "Our backend was hope.",
  "Site uptime: sometimes.",
  "We replaced the CTO with vibes.",
  "The business model was generated by a motivational TikTok."
];

button.addEventListener("click", () => {
  const random = updates[Math.floor(Math.random() * updates.length)];
  message.textContent = random;
});

fundBtn.addEventListener("click", () => {
  alert("Thank you for your investment.\n\nYour money will now be used irresponsibly.");
});

const memes = [
  "deploying to production...",
  "fixing bugs by ignoring them...",
  "asking AI to save the startup...",
  "turning coffee into bad decisions...",
  "optimizing absolutely nothing...",
  "pretending to understand marketing...",
  "downloading another productivity app..."
];

setInterval(() => {
  const random = memes[Math.floor(Math.random() * memes.length)];
  memeText.textContent = random;
}, 2000);

const dvd = document.getElementById("dvd");

let x = 0;
let y = 0;
let dx = 2;
let dy = 2;

function animateDVD() {
  const w = window.innerWidth - 80;
  const h = window.innerHeight - 40;

  x += dx;
  y += dy;

  if (x <= 0 || x >= w) dx *= -1;
  if (y <= 0 || y >= h) dy *= -1;

  dvd.style.left = x + "px";
  dvd.style.top = y + "px";

  requestAnimationFrame(animateDVD);
}

animateDVD();
