create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  business_type text not null,
  source text not null default 'github-pages-homepage',
  created_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;

drop policy if exists "Anyone can join waitlist" on public.waitlist;

create policy "Anyone can join waitlist"
on public.waitlist
for insert
to anon, authenticated
with check (true);
