create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  business_type text not null,
  plan_interest text,
  message text,
  source text not null default 'github-pages-software-demo',
  created_at timestamptz not null default now()
);

alter table public.waitlist add column if not exists plan_interest text;
alter table public.waitlist add column if not exists message text;
alter table public.waitlist add column if not exists source text not null default 'github-pages-software-demo';
alter table public.waitlist add column if not exists created_at timestamptz not null default now();

-- Requested setup: RLS disabled.
alter table public.waitlist disable row level security;

-- Keep public permissions narrow even with RLS disabled.
revoke all on public.waitlist from anon, authenticated;
grant usage on schema public to anon, authenticated;
grant insert on public.waitlist to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Remove older policies if this file is run after the RLS-enabled version.
drop policy if exists "Anyone can join waitlist" on public.waitlist;
drop policy if exists "No public read access" on public.waitlist;
